### ISSUE TITLE
获取用户消息列表及消息详情时的阅读状态是否有误

### ISSUE THREAD

**Issue by wu-xin** [xuanbg/insight_message#1]
获取消息列表或详情时的sql片段：case when r.message_id is null then 0 else 1 end as is_read，因为关联了message_push，查询出来push表的消息都会变成1（已读），是否改成case when r.message_id is null then 0 else r.is_read end as is_read 。取push表的阅读状态？

**Comment by xuanbg** [comment]
啊啊啊，我真是脑子抽了……已修复。感谢！！！

**Comment by wu-xin** [comment]
感觉把template模板表的类型，有效时长等动作变化性的放到scene场景里面会好一点,模板更通用纯粹

**Comment by xuanbg** [comment]
从结构上来讲，场景决定消息内容框架，也就是参数。模板只体现内容的细节。你说的很有道理，我会把结构做一个大的调整。取消模板，把content直接放在场景配置表里面。这样更加简单明了。

发自我的iPhone

在 2020年10月13日，11:16，wu-xin <notifications@github.com> 写道：

﻿

感觉把template模板表的类型，有效时长等动作变化性的放到scene场景里面会好一点,模板更通用纯粹
